### PR TITLE
Add Draggable Message

### PR DESCRIPTION
**Pull request by fpg1503**

### CODE REVIEW

**Review by corujautx — APPROVED** [review]

**Comment by corujautx** [comment]
@fpg1503 have you changed the `Announcement` protocol? The tests aren't passing.

**Review by corujautx — CHANGES_REQUESTED** [review]
The tests aren't passing.

**Comment by fpg1503** [comment]
Oops, I probably screwed something up when I merged master into my branch, I'll check what's wrong and I'll fix it 😅

**Comment by fpg1503** [comment]
Nope, it wasn't the merge, I did add `var tapHandler: ((Self) -> Void)? { get }` to the `Announcement` protocol, do you think I should add an `extension` that returns `nil` by default or move it to another protocol?

**Comment by corujautx** [comment]
@fpg1503 I personally think it's better to add a protocol like `TappableAnnouncement` inheriting from `Announcement` or modifying the protocol itself instead of adding an extension.

**Review by corujautx — APPROVED** [review]

**Pull request merged**
