### PR TITLE
 Improve presentation on iPhone X

### PR DESCRIPTION
**Pull request by fpg1503**

### CODE REVIEW

**Comment by corujautx** [comment]
Doesn’t it makes more sense to adapt the presented views to the safe area inset instead of creating a dummy view to fill the gaps?

**Comment by fpg1503** [comment]
Makes perfect sense, we'll work on it when I get home

**Comment by corujautx** [comment]
Please extend what you did for the other views (with icons/etc).

Also, doesn't making the constraint towards the `safeEdgeLayoutGuide` make the views position correctly?

I was thinking something similar to:

```swift
if #available(iOS 11, *) {
   ...
   let labelTopConstraint = NSLayoutConstraint(
        item: messageLabel,
        attribute: .top,
        relatedBy: .equal,
        toItem: self.safeEdgeLayoutGuide,
        attribute: .top,
        multiplier: 1.0,
        constant: 8.0
    )
    ...
} else {
    ...
    let labelTopConstraint = NSLayoutConstraint(
        item: messageLabel,
        attribute: .top,
        relatedBy: .equal,
        toItem: self,
        attribute: .top,
        multiplier: 1.0,
        constant: 8.0
    )
    ...
}
```

**Comment by fpg1503** [comment]
I was gonna ask you for your opinion before extending the implementation but you beat me to it. I’ll update the implementation to use `safeEdgeLayoutGuide`

**Pull request closed without merging**
